name: Generate My HTML
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and Build
        run: |
          npm install
          npm run build
      - name: Upload HTML Files
        uses: actions/upload-artifact@v4
        with:
          name: my-ready-to-edit-site
          path: out/
